<a href="https://colab.research.google.com/github/balkisoues/DL_Labs/blob/main/TP_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy
from pandas import read_csv
import math
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [19]:
dataframe = read_csv('Covid19X.csv', usecols=[1], engine='python')
dataset = dataframe.values
dataset = dataset.astype('float32')

In [28]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

#print(dataset)

In [21]:
train_size = int(len(dataset) * 0.8)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

40 10


In [43]:
def create_dataset(dataset, look_back=1):
  dataX, dataY = [], []
  for i in range(len(dataset)-look_back-1):
    a = dataset[i:(i+look_back), 0]
    dataX.append(a)
    dataY.append(dataset[i + look_back, 0])
  return numpy.array(dataX), numpy.array(dataY)


In [44]:
look_back = 3
trainX, trainY = create_dataset(train, look_back)
print(trainX)
print(trainY)
testX, testY = create_dataset(test, look_back)

[[0.       0.015625 0.03125 ]
 [0.015625 0.03125  0.046875]
 [0.03125  0.046875 0.0625  ]
 [0.046875 0.0625   0.078125]
 [0.0625   0.078125 0.09375 ]
 [0.078125 0.09375  0.109375]
 [0.09375  0.109375 0.125   ]
 [0.109375 0.125    0.140625]
 [0.125    0.140625 0.15625 ]
 [0.140625 0.15625  0.171875]
 [0.15625  0.171875 0.1875  ]
 [0.171875 0.1875   0.28125 ]
 [0.1875   0.28125  0.296875]
 [0.28125  0.296875 0.3125  ]
 [0.296875 0.3125   0.328125]
 [0.3125   0.328125 0.34375 ]
 [0.328125 0.34375  0.359375]
 [0.34375  0.359375 0.375   ]
 [0.359375 0.375    0.40625 ]
 [0.375    0.40625  0.4375  ]
 [0.40625  0.4375   0.46875 ]
 [0.4375   0.46875  0.5     ]
 [0.46875  0.5      0.53125 ]
 [0.5      0.53125  0.5625  ]
 [0.53125  0.5625   0.59375 ]
 [0.5625   0.59375  0.625   ]
 [0.59375  0.625    0.65625 ]
 [0.625    0.65625  0.6875  ]
 [0.65625  0.6875   0.71875 ]
 [0.6875   0.71875  0.59375 ]
 [0.71875  0.59375  0.609375]
 [0.59375  0.609375 0.625   ]
 [0.609375 0.625    0.640625]
 [0.625   

In [45]:
trainX = numpy.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

In [48]:
model = Sequential()
model.add(SimpleRNN(13, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=100, batch_size=1, verbose=2)

Epoch 1/100
36/36 - 2s - 61ms/step - loss: 0.7804
Epoch 2/100
36/36 - 0s - 3ms/step - loss: 0.3354
Epoch 3/100
36/36 - 0s - 4ms/step - loss: 0.1330
Epoch 4/100
36/36 - 0s - 4ms/step - loss: 0.0653
Epoch 5/100
36/36 - 0s - 6ms/step - loss: 0.0451
Epoch 6/100
36/36 - 0s - 5ms/step - loss: 0.0359
Epoch 7/100
36/36 - 0s - 5ms/step - loss: 0.0306
Epoch 8/100
36/36 - 0s - 5ms/step - loss: 0.0259
Epoch 9/100
36/36 - 0s - 5ms/step - loss: 0.0220
Epoch 10/100
36/36 - 0s - 5ms/step - loss: 0.0186
Epoch 11/100
36/36 - 0s - 8ms/step - loss: 0.0153
Epoch 12/100
36/36 - 0s - 4ms/step - loss: 0.0127
Epoch 13/100
36/36 - 0s - 5ms/step - loss: 0.0106
Epoch 14/100
36/36 - 0s - 5ms/step - loss: 0.0085
Epoch 15/100
36/36 - 0s - 8ms/step - loss: 0.0070
Epoch 16/100
36/36 - 0s - 5ms/step - loss: 0.0057
Epoch 17/100
36/36 - 0s - 6ms/step - loss: 0.0047
Epoch 18/100
36/36 - 0s - 5ms/step - loss: 0.0040
Epoch 19/100
36/36 - 0s - 7ms/step - loss: 0.0032
Epoch 20/100
36/36 - 0s - 3ms/step - loss: 0.0027
Epoch 21

In [49]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 13)             │           221 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            14 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 707 (2.77 KB)

 Trainable params: 235 (940.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 472 (1.85 KB)

In [50]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)
# transformation inverse des prédictions
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])
# calcul du root mean squared error
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.2f RMSE' % (testScore))

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 440ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
Train Score: 0.03 RMSE
Test Score: 0.11 RMSE
